# compose-api.yml  (solo API; BD está fuera en otra VM)
services:
  api:
    build:
      context: .
    env_file:
      - .env
    ports:
      # API escucha 8080 dentro; exponemos 8081 hacia afuera
      - "8081:8080"
    restart: unless-stopped
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8080
      --proxy-headers
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
