services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recetas
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    # NO expongas en prod; para dev puedes dejarlo comentado
    # ports:
    #   - "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro

  catalogo_mock:
    image: python:3.12-slim
    working_dir: /app
    command: bash -lc "pip install fastapi uvicorn && python /app/mock_catalogo.py"
    ports:
      - "8083:8083"
    volumes:
      - ./mock_catalogo.py:/app/mock_catalogo.py:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport sys,urllib.request\ntry:\n  urllib.request.urlopen('http://127.0.0.1:8083/health', timeout=3)\n  sys.exit(0)\nexcept Exception:\n  sys.exit(1)\nPY"
        ]
      interval: 5s
      timeout: 5s
      retries: 30

  recetas_ms:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8080"
    # No dependemos del healthy de mysql; tu app espera con wait_for_db()
    depends_on:
      - mysql
      - catalogo_mock

volumes:
  dbdata:
